"""Add login_provider to user model

Revision ID: 3acefd29fbe4
Revises: 
Create Date: 2024-12-26 21:17:30.760265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3acefd29fbe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_provider', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_provider')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=7), nullable=True),
    sa.Column('subscription_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('subscription_expiry', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('trading_experience', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reset_password_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reset_password_expires', sa.DATETIME(), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('email_verification_token', sa.VARCHAR(length=100), nullable=True),
    sa.Column('failed_login_attempts', sa.INTEGER(), nullable=True),
    sa.Column('account_locked_until', sa.DATETIME(), nullable=True),
    sa.Column('preferences', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_verification_token'),
    sa.UniqueConstraint('reset_password_token'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
